### ISSUE TITLE
Can you share your workflow with frontend, javascript, typescript development

### ISSUE THREAD

**Issue by vpeopleonatank** [windwp/nvim#3]
Firstly, thanks for your contribution to open source community.  Can you share your workflow? anw I 'm also from viet nam :D

**Comment by windwp** [comment]
workflow của mình cũng đơn giản thôi mới chuyển qua neovim với tmux tại rãnh lúc dịch bệnh thôi.
bạn có thể xem stream của tj https://www.twitch.tv/teej_dv

**Comment by vpeopleonatank** [comment]
Cảm ơn bạn nhé :D
